{% set name = "eeglabio" %}
{% set version = "0.0.2.post3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eeglabio-{{ version }}.tar.gz
  sha256: 61a1721ef07dd0619af340a59e3e5e44093b7ed21b447d40f5faed52a2e82b2c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - eeglabio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jackz314/eeglabio
  summary: I/O support for EEGLAB files in Python
  dev_url: https://github.com/jackz314/eeglabio
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jackz314
    - larsoner
    - hoechenberger
