{% set name = "eeglabio" %}
{% set version = "0.0.2.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eeglabio-{{ version }}.tar.gz
  sha256: 2005b4be80005e1eb5c4a82b4e57469bce112e100a813c08d0d9fd5858f431f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - eeglabio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jackz314/eeglabio
  summary: I/O support for EEGLAB files in Python
  dev_url: https://github.com/jackz314/eeglabio
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jackz314
    - larsoner
    - hoechenberger
